---
- name: Prepare all Kubernetes nodes
  hosts: k8s_all
  become: yes
  vars:
    k8s_version: "1.30"
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    # --- НАСТРОЙКА ХОСТОВ И DNS ---
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"

    - name: Add mappings to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.1.52 k8s-master-01
          192.168.1.82 k8s-worker-01
          192.168.1.59 k8s-worker-02
          192.168.1.94 k8s-worker-03
        marker: "# {mark} ANSIBLE MANAGED BLOCK K8S"

    # --- СИСТЕМНЫЕ НАСТРОЙКИ ---
    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Load kernel modules
      shell: |
        cat <<EOF | tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF
        modprobe overlay
        modprobe br_netfilter

    - name: Configure sysctl params
      shell: |
        cat <<EOF | tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF
        sysctl --system

    # --- УСТАНОВКА ЗАВИСИМОСТЕЙ ---
    - name: Install required basic packages
      apt:
        name: [apt-transport-https, ca-certificates, curl, gpg, gnupg]
        state: present
        update_cache: yes

    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # --- ИСПРАВЛЕННАЯ СЕКЦИЯ DOCKER ---
    - name: Remove old Docker GPG key if exists (cleanup)
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644' # ВАЖНО: Права на чтение для всех
        force: yes

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    # Обновляем кэш принудительно после добавления репо
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install containerd
      apt:
        name: containerd.io
        state: present

    - name: Configure containerd
      shell: |
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
      notify: Restart containerd

    # --- УСТАНОВКА KUBERNETES ---
    - name: Download Kubernetes GPG key
      get_url:
        url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
        dest: /tmp/kubernetes-apt-keyring.key

    - name: Armor Kubernetes GPG key
      shell: cat /tmp/kubernetes-apt-keyring.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes

    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
        state: present
        filename: kubernetes

    - name: Install kubelet, kubeadm, kubectl
      apt:
        name: [kubelet, kubeadm, kubectl]
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: [kubelet, kubeadm, kubectl]

  handlers:
    - name: Restart containerd
      service:
        name: containerd
        state: restarted
