---
- name: Deploy Demo App (Yandex Mirror)
  hosts: k8s_master
  become: yes
  tasks:
    - name: Deploy App and Service
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        
        # Чистим старое
        kubectl delete deployment hello-kubernetes --ignore-not-found=true
        kubectl delete service hello-kubernetes-service --ignore-not-found=true
        
        # Создаем Deployment (используем зеркало Яндекса)
        cat <<EOF | kubectl apply -f -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: hello-kubernetes
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: hello-kubernetes
          template:
            metadata:
              labels:
                app: hello-kubernetes
            spec:
              containers:
              - name: hello-kubernetes
                # Используем зеркало Яндекса для Nginx (оно точно доступно)
                image: cr.yandex/mirror/nginx:alpine
                ports:
                - containerPort: 80
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: hello-kubernetes-service
        spec:
          ports:
          - port: 80
            targetPort: 80
          selector:
            app: hello-kubernetes
        EOF
