---
- name: Deploy Demo App (No Ingress)
  hosts: k8s_master
  become: yes
  tasks:
    - name: Deploy App and Service
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        
        # Создаем Deployment (само приложение)
        kubectl create deployment demo-app --image=httpd:alpine --replicas=2 --dry-run=client -o yaml | kubectl apply -f -
        
        # Создаем Service (сетевой доступ внутри кластера)
        kubectl expose deployment demo-app --port=80 --target-port=80 --type=ClusterIP --dry-run=client -o yaml | kubectl apply -f -
